Spyral Fix
Ygoproco/Live2017 pull request #193
Opened 2017-04-18 04:36 UTC by KServantes

Updated SPYRAL Sleeper text in database to "Must be Special Summoned."
Fixed SPYRAL Sleeper and SPRYAL GEAR - Last Resort scripts.

2017-04-18 15:49 UTC, TheOnePharaoh requested changes

2017-04-18 15:49 UTC, TheOnePharaoh commented on script/c100912086.lua
> +	c:EnableUnsummonable()
You shouldn't remove the revive limit

2017-04-18 15:49 UTC, TheOnePharaoh commented on script/c100912086.lua
> +	c:EnableUnsummonable()
also it's best to leave the changes in the beta cards to Eerie

2017-04-18 15:53 UTC, TheOnePharaoh commented
also it's best to leave the changes in the beta cards to Eerie

2017-04-18 19:23 UTC, KServantes commented on script/c100912086.lua
> +	c:EnableUnsummonable()
It's not a Semi-Nomi.

2017-04-18 19:59 UTC, EerieCode commented
Honestly, @KServantes , my biggest issue here is that, with whatever you did to the formatting, it's hard to see what exactly has been changed. If you could change the formatting so that we see only the things you've changed, that'd definitely make things easier. That said, I do have a few things to say:

- Why _c:EnableUnsummonable()_ in Sleeper? It's a Nomi monster, kinda like "Dystopia the Despondant": that's the whole reason for the text change. c:EnableReviveLimit() should suffice.
- There's a bug we both missed in Last Resort: at the end of the .dircost function, you should add _Duel.SendtoGrave(g,REASON_COST)_ to fix the cost.

I'll tell you if I find anything else after you upload the reformatted files: if you can't do that, I can upload these fixes along with the new cards in about 8 hours: in which case, it'd be better to close this branch to avoid a huge conflict.

2017-04-18 20:17 UTC, KServantes commented
@EerieCode No idea why the formatting came out that way really but I'll reopen a new pull later.

2017-04-19 02:20 UTC, closed without merging

2017-04-19 10:00 UTC, TheOnePharaoh commented
it would be best if Eerie did it because he can check any fixes made in fluo as well

2017-04-19 10:02 UTC, EerieCode commented
https://github.com/Ygoproco/Live2017/pull/197

He already made the new pull, I've already checked it and it should be fine